### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by MrNunoski** [bdc11/Ebates#1]
Hi Brandon,

I tried running your script in both python and python3 but neither worked. Perhaps I am doing something wrong or there might be an error?

`ngoncalves$ python ebates_hw.py 
Traceback (most recent call last):
  File "ebates_hw.py", line 1, in <module>
    import requests, json
ImportError: No module named requests`

`ngoncalves$ python3 ebates_hw.py 
  File "ebates_hw.py", line 25
    print 'The number of hd keys true: %s' %hd_true
                                         ^
SyntaxError: Missing parentheses in call to 'print'`

**Comment by bdc11** [comment]
Hi Nuno,

Sorry, I forgot to include that requests module is not native to python. In order to run it you'll need to install requests module. You can do this by using: pip install requests

I will update my github with a requirements.txt file to include all my dependencies since I forgot them. Sorry for the mix up.

**Comment by MrNunoski** [comment]
Thanks Brandon,

Was hoping you had a way to do this without sudo..  :)

Here's the output I get.. 

`ngoncalves$ python ebates_hw.py 
The number of hd keys true: 10000
The number of hd keys false: 0
http://api.viki.io/v4/videos.json?app=100250a&per_page=10&page=1000`

**Comment by bdc11** [comment]
Hi Nuno,

Did **pip3 install requests** not work for you? Although I know it's not the best practice, I felt it was the easiest way to at least get the module to run the script. 

Yeah, sorry. I ended up suggesting sudo in order to get around security permissions that I came across on my laptop that wouldn't import the module. 

Awesome! That's the output I'm getting as well. Hopefully it didn't run too slow. I edited the API so that it wouldn't take awhile to scan through and iterate pages.
